# Generated by Django 4.1.6 on 2023-02-10 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('text_comment', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dawrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('photo_url', models.TextField(blank=True, max_length=5000, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Film_app.comments')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
