# Generated by Django 4.1.6 on 2023-02-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film_app', '0003_dawrat_description_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMainHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.TextField(blank=True, max_length=5000, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
