# Generated by Django 4.1.6 on 2023-02-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Film_app', '0004_postmainhome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('pro', 'Pro'), ('enterprise', 'Enterprise')], max_length=50, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('program_of_offre1', models.CharField(blank=True, max_length=200)),
                ('program_of_offre2', models.CharField(blank=True, max_length=200)),
                ('program_of_offre3', models.CharField(blank=True, max_length=200)),
                ('program_of_offre4', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
