# Generated by Django 4.1.6 on 2023-02-11 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Film_app', '0007_alter_comments_options_comments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dawrat',
            name='com',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Film_app.comments'),
        ),
    ]
