# Generated by Django 4.1.6 on 2023-02-11 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Film_app', '0008_alter_dawrat_com'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dawrat',
            name='com',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Film_app.comments'),
        ),
    ]
